# Generated by Django 2.1.5 on 2021-03-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listView', '0004_auto_20210312_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
